on: push

name: Void Deploy

jobs:
  purge:
    name: Purge Old Jobs
    runs-on: ubuntu-latest
    steps:
        # Use this GitHub Actions at least once in this workflow as soon as possible.
      - uses: benwart/auto-cancel-redundant-workflow@master
        with:
          WORKFLOW_RUN_STATUS_FILTER: waiting


  deploy:
    environment: void
    name: Deploy to Void
    runs-on: ubuntu-latest
    steps:
      - name: Echo "Hello World"
        run: echo "Hello World"
